### ISSUE TITLE
Source for Hex

### ISSUE THREAD

**Issue by aracnid** [tomkontra/beer-color#1]
Could you site the source for the SRM to RGB mapping? I can't seem to find a standard anywhere. I'd like to create a standard if there isn't one already.

**Comment by tomkontra** [comment]
Sadly I have no idea where I got the mapping from. I found it somewhere years ago, added some missing values to it and used it in a private project before I created this package. I tried to find the original mapping now, but none of the ones I can find match with what I've used. I don't think that a standard exists, and creating one is pretty difficult as SRM only represents one point in the color spectrum of a beer and fails to capture the others. Thus the best one can do is to create a range of "beery" colors from very pale to very dark that give a reasonable approximation of the expected color.
